services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py
  ollama:
    image: ollama/ollama
    volumes:
      - .:/root/.ollama
    ports:
      - "11434:11434"
    command: /bin/sh -c "cd /root/.ollama/commands && ./ollama-postcreated.sh"